package com.Kmongo.utils
const val TASK_DB = "task_manger"
const val TASK_COLLECTION = "tasks"
const val TITLE = "title"
const val DESCRIPTION = "description"
const val START_DATE = "startDate"
const val END_DATE = "endDate"
const val PRIORITY = "priority"
const val STATUS = "status"
const val ID = "_id"